name: CI
on:
  push:
    branches:
      - feature1

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v2
          with:
            distribution: 'zulu'
            java-version: '11'
        - uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.7.7'
        - run: flutter pub get
        - run: flutter analyze
        - run: flutter test
    
